<?php

return [
    'guides' => [
        [
            'image' => 'learn/zero-knowledge-encryption.jpg',
            'slug' => 'zero-knowledge-encryption',
            'title' => 'Zero-Knowledge Encryption: What It Means, How It Works, and Why It Matters',
            'description' => 'A practical guide to zero-knowledge encryption: what it means, why it exists, how it works, and the tradeoffs to plan for.',
            'route' => 'learn.zero-knowledge-encryption',
            'tags' => [
                'security',
                'zero-knowledge',
                'encryption',
                'architecture',
            ],
            'keywords' => [
                'zero knowledge encryption',
                'client-side encryption',
                'zero knowledge architecture',
                'encryption tradeoffs',
                'key management strategy',
            ],
        ],
        [
            'image' => 'learn/laravel-env-example.png',
            'slug' => 'laravel-env-example',
            'title' => 'Laravel .env.example — The Definitive Guide',
            'description' => 'A complete reference for understanding, creating, and maintaining .env.example files the right way — including security, team workflows, and conventions.',
            'route' => 'learn.laravel-env-example',
            'tags' => [
                'laravel',
                'env-files',
                'security',
                'configuration',
            ],
            'keywords' => [
                'laravel env example',
                'dotenv',
                'environment variables',
                'secrets management',
                'configuration management',
            ],
        ],
        [
            'image' => 'learn/laravel-multi-env-secrets.jpg',
            'slug' => 'laravel-multi-environment-secrets',
            'title' => 'Laravel Multi-Environment Secrets Strategy',
            'description' => 'A practical, real-world guide to managing Laravel configuration and secrets across local, staging, and production—without leaks or drift.',
            'route' => 'learn.laravel-multi-environment-secrets',
            'tags' => [
                'laravel',
                'secrets-management',
                'configuration',
                'devops',
            ],
            'keywords' => [
                'laravel multi environment',
                'laravel staging env',
                'secrets management laravel',
                'laravel config best practices',
                'dotenv strategies',
            ],
        ],
        [
            'image' => 'learn/env-variable-naming-conventions.jpg',
            'slug' => 'env-naming-conventions',
            'title' => 'ENV Variable Naming Conventions & Best Practices',
            'description' => 'A concise guide to consistent, portable, collision-free environment variable naming that works across languages and teams.',
            'route' => 'learn.env-naming-conventions',
            'tags' => [
                'configuration',
                'secrets-management',
                'naming',
                'devops',
            ],
            'keywords' => [
                'env variable naming',
                'environment variable best practices',
                'config naming standards',
                'secrets naming conventions',
                'screaming snake case env',
            ],
        ],
    ],
    'tutorials' => [
        [
            'image' => 'learn/validate-your-env-files-with-ghostable.jpg',
            'slug' => 'env-validation-tutorial',
            'title' => 'Validate your .env files with Ghostable',
            'description' => 'Step-by-step tutorial for setting up Ghostable schema validation, adding framework-specific rules, and wiring checks into deploys.',
            'route' => 'learn.env-validation-tutorial',
            'tags' => [
                'validation',
                'env-files',
                'ci-cd',
                'configuration',
            ],
            'keywords' => [
                'ghostable validation tutorial',
                'env validation rules',
                'schema yaml',
                'ci cd env validation',
                'laravel env validation',
                'nextjs env validation',
            ],
        ],
        [
            'image' => 'learn/your-first-deploy-with-ghostable.jpg',
            'slug' => 'first-deploy-with-ghostable',
            'title' => 'Your first deploy with Ghostable',
            'description' => 'Hands-on walkthrough to prepare, validate, and ship your first deploy using Ghostable-powered environments.',
            'route' => 'learn.first-deploy-with-ghostable',
            'tags' => [
                'deployments',
                'ci-cd',
                'env-files',
                'ghostable-cli',
            ],
            'keywords' => [
                'ghostable deploy tutorial',
                'first deploy ghostable',
                'ci cd ghostable',
                'env push deploy',
                'deploy token ghostable',
            ],
        ],
        [
            'image' => 'learn/linking-and-unlinking-devices.jpg',
            'slug' => 'linking-devices',
            'title' => 'Linking and unlinking devices the right way',
            'description' => 'How device linking powers zero-knowledge encryption, plus onboarding and offboarding steps for your team.',
            'route' => 'learn.linking-devices',
            'tags' => [
                'security',
                'devices',
                'zero-knowledge',
                'onboarding',
            ],
            'keywords' => [
                'ghostable device link',
                'ghostable device unlink',
                'zero knowledge devices',
                'offboarding ghostable',
                'device status ghostable',
            ],
        ],
    ],
];
